DROP DATABASE IF EXISTS employeetracker_db;
CREATE DATABASE employeetracker_db;

USE employeetracker_db;

CREATE TABLE departments (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
dep_name VARCHAR(30) NOT NULL
);

CREATE TABLE roles (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
dep_id INT,

FOREIGN KEY (dep_id)
REFERENCES departments(id)
ON DELETE CASCADE
);

CREATE TABLE employees (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT,
manager_id INT,

FOREIGN KEY (role_id) 
REFERENCES roles(id)
ON DELETE CASCADE,

FOREIGN KEY (manager_id) 
REFERENCES employees(id)
ON DELETE SET NULL
);